name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Change directory and build Docker image
      run: docker build. --file Dockerfile --tag my-image-name:$(date +%s)
      working-directory: Server/Java
